'''
The "Collatz Sequence" of a number is the sequence generated by following the procedure outlined in the Collatz conjecture. Find the the number (less than 1 million) which generates the longest such sequence
'''

def collseq(first):
    curr=first
    length = 1
    while curr != 1:
        if curr%2==0:
            curr = curr/2
        else:
            curr = 3*curr+1
        length+=1
    return (length,first)

def maxlength():
    max, start = 1,1
    for e in range(1,1000000):
        (currlength,currfirst) = collseq(e)
        if currlength>max:
            max = currlength
            start = currfirst
    return start

print(maxlength())
